FROM node:23-alpine

WORKDIR /src

COPY package*.json ./

ENV PORT=3000 \ 
    MEDIA_SERVICE_URL=http://media:3001 \
    DOCUMENT_SERVICE_URL=http://document:3002 \ 
    JELLYFIN_URL=http://host.docker.internal:8096 \
    ORIGIN=http://deesnotes.cloud \
    DATABASE_URL=postgresql://postgres:prisma@host.docker.internal:5432/postgres?schema=public 

RUN npm install 

COPY ./src ./src
COPY ./prisma ./prisma
COPY tsconfig.json tsconfig.json

RUN npm run build
RUN npx prisma generate deploy
RUN npx prisma generate

WORKDIR /src/dist

# Stage 2: run the application as user node
USER node

EXPOSE ${PORT}

CMD ["node", "index.js"]