version: "0.1"

networks:
  private_net:
    driver: bridge
    internal: true # Makes the network isolated from external docker-compose file
  public_net:
    driver: bridge

services:
  ############################################################
  ### private services, only accessible by 'public-gateway'###
  ############################################################

  # media gateway - the gateway for public gateway to access media service:
  media:
    build:
      context: ./media-service
      dockerfile: dockerfile
    container_name: media
    networks:
      - private_net
  # jellyfin - the media server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    # Add in the UID and GID that you would like to run jellyfin as in the user line below, or remove the user line to use the default (root).
    # user: uid:gid
    # network_mode: "host"
    volumes:
      - /path/to/config:/usr/local/bin/jellyfin/config
      - /path/to/cache:/usr/local/bin/jellyfin/cache
      - type: bind
        source: /usr/local/bin/jellyfin/media
        target: /media
      - type: bind
        source: /usr/local/bin/jellyfin/media2
        target: /media2
        read_only: true
    # ports:
    #   - "8096:8096"
    restart: unless-stopped
    networks:
      - private_net

  document:
    build:
      context: ./document-service
      dockerfile: dockerfile
    container_name: document
    networks:
      - private_net

  #######################
  ### public services ###
  #######################
  public-gateway:
    container_name: public-gateway
    build:
      context: ./public-gateway
      dockerfile: dockerfile
    ports:
      - "4300:4300"
    networks:
      - private_net
      - public_net
  cloudflare-ddns:
    build:
      context: ./cloudflare-ddns
      dockerfile: dockerfile
    container_name: cloudflare-ddns
    volumes:
      - ./cloudflare-ddns:/usr/local/bin/cloudflare-ddns
    restart: unless-stopped
  app:
    build:
      context: ./nginx
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
    # Uncomment this if you want to change the location of
    # the SQLite DB file within the container
    # DB_SQLITE_FILE: "/data/database.sqlite"

    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'

    volumes:
      - ./nginx/data:/etc/nginx/data
      - ./nginx/letsencrypt:/etc/nginx/letsencrypt
