version: "0.1"
services:
  media:
    build:
      context: ./media-service
      dockerfile: dockerfile
    ports:
      - "4300:3000"
  cloudflare-ddns:
    build:
      context: ./cloudflare-ddns
      dockerfile: dockerfile
    container_name: cloudflare-ddns
    volumes:
      - ./cloudflare-ddns.sh:/usr/local/bin/cloudflare-ddns.sh
    restart: unless-stopped
