version: "0.1"
services:
  media:
    build:
      context: ./media-service
      dockerfile: dockerfile
    ports:
      - "4300:3000"
  cloudflare-ddns:
    build:
      context: ./cloudflare-ddns
      dockerfile: dockerfile
    container_name: cloudflare-ddns
    volumes:
      - ./cloudflare-ddns:/usr/local/bin/cloudflare-ddns
    restart: unless-stopped
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
    # Uncomment this if you want to change the location of
    # the SQLite DB file within the container
    # DB_SQLITE_FILE: "/data/database.sqlite"

    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'

    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
