http:
  middlewares:
    check-origin:
      headers:
        customRequestHeaders:
          X-Traefik-Original-Origin: "{req.headers.Origin}"
        customResponseHeaders:
          X-Traefik-Origin-Check: "Failed"
        accessControlAllowHeaders: "*" # Allow all headers
        accessControlAllowOriginList:
          - "http://deesnotes.cloud"
        addVaryHeader: true
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"

    delay-middleware:
      plugin:
        plugin-simple:
          delay: 3s

  routers:
    public-gateway:
      rule: "Host(`deesnotes.com`)"
      entryPoints:
        - web
        - websecure
      service: public-gateway
      middlewares:
        - "check-origin"
        - "delay-middleware"

  services:
    public-gateway:
      loadBalancer:
        servers:
          - url: "http://192.168.1.157:4300"
