FROM node:22-alpine

WORKDIR /src

# Delete node_modules and package-lock.json for a clean install
# RUN rm -rf node_modules

COPY . .

RUN npm install 
RUN npm run build

ENV port=3000
EXPOSE 3000
CMD ["npm", "run", "start"]