# Stage 1: build the application
FROM node:23-alpine AS builder

COPY /default-gateway/package*.json ./
COPY /default-gateway/src ./src
COPY /default-gateway/tsconfig.json ./
COPY /default-gateway/prisma ./prisma

ENV PORT=3001 \
    DATABASE_URL=postgresql://postgres:prisma@host.docker.internal:5432/media?schema=public

RUN npm ci

RUN npx prisma generate
RUN npx prisma db push

# Stage 2: run the application as user node
FROM node:23-alpine

ENV PORT=3001 \
    DATABASE_URL=postgresql://postgres:prisma@host.docker.internal:5432/media?schema=public

COPY --from=builder /dist ./dist
COPY --from=builder /prisma ./prisma
COPY --from=builder /node_modules ./node_modules
COPY package*.json ./

WORKDIR /dist

USER node

EXPOSE ${PORT}

CMD ["node", "index.js"]