FROM node:22 AS build

WORKDIR /src

ENV PORT=5173 \
    VITE_API_BASE_URL=http://localhost:3000

COPY . .

RUN npm install 
RUN npm run build

FROM node:22-alpine

WORKDIR /src

COPY --from=build /src/dist /src

RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", ".", "-l", "5173"]