FROM node:23-alpine

WORKDIR /default-gateway

COPY /default-gateway/package*.json ./

ENV PORT=3002

RUN npm install 

COPY /default-gateway/src ./src
COPY /default-gateway/tsconfig.json tsconfig.json

RUN npm run build

WORKDIR /default-gateway/dist

USER node

EXPOSE ${PORT}

CMD ["node", "index.js"]