FROM node:23-alpine

WORKDIR /default-gateway

COPY package*.json ./

ENV PORT=3002 \ 
    DATABASE_URL=postgresql://postgres:prisma@host.docker.internal:5432/document?schema=public 

RUN npm install 

COPY /src ./src
COPY /tsconfig.json ./

RUN npm run build

WORKDIR /default-gateway/dist

USER node

EXPOSE ${PORT}

CMD ["node", "index.js"]